### ISSUE TITLE
gulp-watch crashes through chokidar

### ISSUE THREAD

**Issue by XemsDoom** [floatdrop/gulp-watch#154]
Hi, gulp-watch crashes when deleting files and re-executing a task.

Per default, gulp will automatically copy js files from the `src` into the `target` folder, this happens in the `transpileClientJS` task. In that task, gulp-watch will pipe files through babel and then ouput them to the `target` folder.

```
gulp.task('transpileClientJS', function(){
    gulp.src(sourcePaths.client.js)
    .pipe(watch(sourcePaths.client.js))
    .pipe(plumber())
    .pipe(babel())
    .pipe(gulp.dest(destPaths.client.js))
    .pipe(notify('transpiled client js6 files'));
});
```

If you create a folder in `src/client/js`, for example 'test' and a file in that folder called `test.js`, the task will successfully copy the test.js file into `target/client/js/test/test.js`. The problem comes when trying to remove files. If I now delete the file 'test.js' and folder 'test' in `src/client/js` the task will still work. However, if I now save/update another file in `src/client/js` gulp-watch will crash through chokidar:

```
D:\Projects\webgl\node_modules\gulp-watch\node_modules\chokidar\lib\nodefs-handl
er.js:89
      if (ÓñàÓñ¿ÓñÖÓÑÂÓÑ╗ÓÑÜÓÑØ.platform === 'win32' && ÓñúÓñÖÓñøÓñïÓñÄ.code ===
 'EPERM') {
          ^
ReferenceError: ÓñàÓñ¿ÓñÖÓÑÂÓÑ╗ÓÑÜÓÑØ is not defined
    at FSWatcher.<anonymous> (D:\Projects\webgl\node_modules\gulp-watch\node_mod
ules\chokidar\lib\nodefs-handler.js:89:11)
    at FSWatcher.emit (events.js:107:17)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1161:12)
```
Normally gulp-watch should then simply stream the only available files further downside the pipe instead of crashing. And yes `ÓñàÓñ¿ÓñÖÓÑÂÓÑ╗ÓÑÜÓÑØ` is really what's in the console.

Versions:
* gulp 3.8.11
* gulp-watch 4.2.2
* NodeJS 0.12.1

This is my complete gulpfile:
```
var fs = require('fs');
var path = require('path');
var gulp = require('gulp');
var async = require('async');
var out = require('gulp-out');
var zip = require('gulp-zip');
var sass = require('gulp-sass');
var gutil = require('gulp-util');
var newer = require('gulp-newer');
var watch = require('gulp-watch');
var babel = require('gulp-babel');
var watchify = require('watchify');
var uglify = require('gulp-uglify');
var concat = require('gulp-concat');
var notify = require("gulp-notify");
var buffer = require('vinyl-buffer');
var plumber = require('gulp-plumber');
var dateFormat = require('dateformat');
var browserify = require('browserify');
var source = require('vinyl-source-stream');
var sourcemaps = require('gulp-sourcemaps');
var livereload = require('gulp-livereload');
var autoprefixer = require('gulp-autoprefixer');

// source paths
var sourcePaths = {
	client: {
		img: [
			'src/client/imgs/**/*.png',
			'src/client/imgs/**/*.jpg',
			'src/client/imgs/**/*.ico'
		],
		css: 'src/client/css/**/*.scss',
		js: 'src/client/js/**/*.js'
	},
	config: 'src/config/**/*.json',
	server: {
		js: 'src/server/**/*.js',
		views: 'src/server/**/*.jade'
	}
};

// destination paths
var destPaths = {
	client: {
		img: 'target/client/imgs',
		css: 'target/client/css',
		js: 'target/client/js',
		jsTargets: ['target/client/js/**/*.js', '!target/client/js/client.js'],
		entryPoint: './target/client/js/client.js',
		browserifyTarget: 'target/client/js'
	},
	config: 'target/config',
	server: {
		js: 'target/server',
		views: 'target/server'
	}
};

// production files
var productionFiles = [
	'target/client/css/*',
	'target/client/imgs/*',
	'target/client/js/bundle.js',
	'target/config/*',
	'target/server/**/*'
];

// temp files
var tempFolder = '_temp';
var tempFiles = [
	tempFolder+'/client/css/*',
	tempFolder+'/client/imgs/*',
	tempFolder+'/client/js/bundle.js',
	tempFolder+'/config/*',
	tempFolder+'/server/**/*',
	tempFolder+'/package.json'
];

// tasks
gulp.task('transpileClientCSS', function () {
	gulp.src(sourcePaths.client.css)
	.pipe(watch(sourcePaths.client.css))
	.pipe(plumber())
	.pipe(sass({errLogToConsole: true}))
	.pipe(autoprefixer())
	.pipe(gulp.dest(destPaths.client.css))
	.pipe(notify('transpiled client scss files'))
	.pipe(livereload());
});

gulp.task('transpileClientJS', function(){
	gulp.src(sourcePaths.client.js)
	.pipe(watch(sourcePaths.client.js))
	.pipe(plumber())
	.pipe(babel())
	.pipe(gulp.dest(destPaths.client.js))
	.pipe(notify('transpiled client js6 files'));
});

gulp.task('transpileServerJS', function(){
	gulp.src(sourcePaths.server.js)
	.pipe(watch(sourcePaths.server.js))
	.pipe(plumber())
	.pipe(babel())
	.pipe(gulp.dest(destPaths.server.js))
	.pipe(notify('transpiled server js6 files'))
	.pipe(livereload());
});

// browserify gets a little more complicated
var bundler = watchify(browserify(watchify.args));
bundler.add(destPaths.client.entryPoint);
bundler.on('update', bundle);
bundler.on('log', gutil.log);

function bundle(){
	return bundler.bundle()
	.on('error', gutil.log.bind(gutil, 'Browserify Error'))
	.pipe(plumber())
	.pipe(source('bundle.js'))
	.pipe(gulp.dest(destPaths.client.browserifyTarget))
	.pipe(livereload())
	.pipe(notify('browserified client js files'));
}

gulp.task('browserifyClientJS', bundle);

// copy tasks
gulp.task('copyConfig', function(){
	gulp.src(sourcePaths.config)
	.pipe(watch(sourcePaths.config))
	.pipe(gulp.dest(destPaths.config))
	.pipe(notify('copied config files to target'));
});

gulp.task('copyJadeViews', function(){
	gulp.src(sourcePaths.server.views)
	.pipe(watch(sourcePaths.server.views))
	.pipe(gulp.dest(destPaths.server.views))
	.pipe(notify('copied jade views files to target'))
	.pipe(livereload());
});

gulp.task('copyImages', function(){
	gulp.src(sourcePaths.client.img)
	.pipe(watch(sourcePaths.client.img))
	.pipe(gulp.dest(destPaths.client.img))
	.pipe(notify('copied image files to target'))
	.pipe(livereload());
});

// livereload to reload the browser on file changes
gulp.task('livereload', function(){
	livereload.listen({start: true});
});

// scaffolding task
var mkdirSync = function(path){
	if(!fs.existsSync(path)){
		try{
			gutil.log('creating directory: ' + path);
			fs.mkdirSync(path);
		}catch(err){
			throw Error(err);
		}
	}
};

var mkdirSyncRecursive = function (dirpaths){
	for(var x = 0; x < dirpaths.length; x++){
		var dirpath = dirpaths[x];		
		var parts = dirpath.split(path.sep);
		for(var i = 1; i <= parts.length; i++){
			mkdirSync(path.join.apply(null, parts.slice(0, i)));
		}
	}
};

var rmdir = function(dir) {
	if(!fs.existsSync(dir)){
		return;
	}
	var list = fs.readdirSync(dir);
	for(var i = 0; i < list.length; i++) {
		var filename = path.join(dir, list[i]);
		var stat = fs.statSync(filename);
		
		if(filename == "." || filename == "..") {
		} else if(stat.isDirectory()) {
			rmdir(filename);
		} else {
			fs.unlinkSync(filename);
		}
	}
	fs.rmdirSync(dir);
};

gulp.task('scaffold', function(){
	// create directories
	mkdirSyncRecursive([
		'src/client/js/collections',
		'src/client/js/models',
		'src/client/js/various',
		'src/client/js/views',
		'src/server/models',
		'src/server/utils',
		'target/client/js/collections',
		'target/client/js/models',
		'target/client/js/various',
		'target/client/js/views',
		'target/server/models',
		'target/server/utils'
	]);
});

// production build task
gulp.task('prod', function(){

	// get build time
	var buildTime = dateFormat(new Date(), 'dd-mm-yyyy-h-MM-ss-');

	// create a temp dir for copying all the files
	rmdir(tempFolder);
	mkdirSync(tempFolder);

	// start building
	async.series([
		// copy files to temp dir
		function(cb){
			var s = new Date();
			gutil.log('copying files to temp folder...');
			gulp.src(productionFiles, {base: 'target/'})
			.pipe(gulp.dest(tempFolder))
			.on('end', function(){
				gutil.log('copyied files to temp folder, took '+(new Date() - s)+'ms');
				cb();	
			});
		},
		// copy package.json
		function(cb){
			var s = new Date();
			gulp.src('package.json')
			.pipe(gulp.dest(tempFolder))
			.on('end', cb);
		},
		// uglify bundle.js
		function(cb){
			var s = new Date();
			gutil.log('uglifying bundle.js...');
			gulp.src(tempFolder+'/client/js/bundle.js')
			.pipe(uglify())
			.pipe(gulp.dest(tempFolder+'/client/js/'))
			.on('end', function(){
				gutil.log('uglified bundle.js, took '+(new Date() - s)+'ms');
				cb();
			});
		},
		// zip temp dir
		function (cb){
			var s = new Date();
			gutil.log('zipping temp folder...');
			gulp.src(tempFiles, {base: tempFolder+'/'})
			.pipe(zip('production-'+buildTime+'.zip'))
			.pipe(gulp.dest('dest'))
			.on('end', function(){
				gutil.log('zipped temp folder, took '+(new Date() - s)+'ms');
				cb();	
			});
		},
		// remove the temp dir
		function(cb){
			rmdir(tempFolder);
			gutil.log('removed temp folder');
			cb();
		}
	], function(err, results){
		gutil.log(gutil.colors.green('successfully created production build'));
		gutil.log(gutil.colors.green('=> production-'+buildTime+'.zip'));
	});
});

// default: watch over source directories and compile files in case of changes
gulp.task('default', [
	'livereload', 
	'transpileClientCSS', 
	'transpileClientJS', 
	'transpileServerJS', 
	'browserifyClientJS', 
	'copyConfig', 
	'copyJadeViews',
	'copyImages'
]);
```

Note, if I set the `plumber()` pipe piece before the watch pipe, it will just omit the error, but I think gulp-watch shouldnt even throw an error.

**Comment by floatdrop** [comment]
Run `npm update` - seems like chokidar is out of date (by stacktrace).

**Comment by XemsDoom** [comment]
In gulp-watch's node_modules folder, chokidar version 1.0.0-rc6 is installed. That's the current version.

**Comment by floatdrop** [comment]
@XemsDoom then I got no better idea, than open this issue in [chokidar](https://github.com/paulmillr/chokidar) repository - it is clear by stacktrace, that problem in `D:\Projects\webgl\node_modules\gulp-watch\node_modules\chokidar\lib\nodefs-handler.js:89`.

**Comment by XemsDoom** [comment]
@floatdrop you should consider removing chokidar 1.0.0-rc6 as a dependency, because it's a stupid April fool joke: https://github.com/paulmillr/chokidar/pull/272

**Comment by floatdrop** [comment]
@XemsDoom freezed chokidar version to `1.0.0-rc5`.

**Comment by paulmillr** [comment]
@XemsDoom @floatdrop Sorry folks, we didn't know someone actually depends on git version for their plugins. A joke went too far I guess.

**Comment by XemsDoom** [comment]
@paulmillr 
we just lost 20$ Million  because of your joke in our production environment 
¯\\_(ツ)_/¯

**Comment by floatdrop** [comment]
@XemsDoom found them ![1105449_120621154530_z10](https://cloud.githubusercontent.com/assets/365089/6993648/8596f540-db14-11e4-96b8-7f0d6d4e9461.jpg)
