### ISSUE TITLE
Error: EMFILE: Too many opened files on Node 0.10.36

### ISSUE THREAD

**Issue by elfenheart** [floatdrop/gulp-watch#158]
I am getting the following error when doing gulp watch:

```
[10:57:08] Error: EMFILE: Too many opened files.
    at Gaze._handleError (/Users/edwinelia/source/cdap/cdap-ui/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:436:31)
    at Gaze._watchDir (/Users/edwinelia/source/cdap/cdap-ui/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:302:17)
    at /Users/edwinelia/source/cdap/cdap-ui/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:358:10
    at iterate (/Users/edwinelia/source/cdap/cdap-ui/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:52:5)
    at /Users/edwinelia/source/cdap/cdap-ui/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:61:11
    at /Users/edwinelia/source/cdap/cdap-ui/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:420:5
    at iterate (/Users/edwinelia/source/cdap/cdap-ui/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:52:5)
    at /Users/edwinelia/source/cdap/cdap-ui/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:61:11
    at /Users/edwinelia/source/cdap/cdap-ui/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:420:5
    at iterate (/Users/edwinelia/source/cdap/cdap-ui/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/helper.js:52:5)
```

Node version I am using: 0.10.36. When I switch to version 0.12, this problem disappear.

**Comment by floatdrop** [comment]
This issue is with bundled `watch` function - `/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:436:31`, reopen it here: https://github.com/gulpjs/gulp/issues/
