### ISSUE TITLE
EventEmitter memory leak

### ISSUE THREAD

**Issue by simoami** [floatdrop/gulp-watch#169]
Hello,

I'm getting a "EventEmitter memory leak" error periodically. I'm not sure what's the root cause but it involves the gulp-watch task. I'm hoping you can help troubleshoot:

my task:
```
gulp.task('watch', function() {

  plug.watch('client/assets/less/**/*.less', function() {
    log('*************************************');
    log('Change detected in CSS. Rebuilding...');
    plug.runSequence('build-less', 'copy-css');
  });

  plug.watch('client/views/**/*', function() {
    log('*************************************');
    log('Change detected in Views. Rebuilding...');
    plug.runSequence('build-views', 'copy-js');
  });

  plug.watch('gulpfile.js', function() {
    log('*************************************');
    log('Change detected in gulpfile.js. Rebuilding...');
    gulp.start('build');
  });

});
```

And the error happens after a few iterations
```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Gulp.addListener (events.js:160:15)
    at runSequence (./node_modules/run-sequence/index.js:87:7)
    at ./gulpfile.js:294:10
    at write (./node_modules/gulp-watch/index.js:93:9)
    at ./node_modules/gulp-watch/node_modules/vinyl-file/index.js:51:4
    at evalmachine.<anonymous>:271:14
    at ./node_modules/gulp-watch/node_modules/vinyl-file/node_modules/graceful-fs/graceful-fs.js:102:5
    at Object.oncomplete (evalmachine.<anonymous>:107:15)
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Gulp.addListener (events.js:160:15)
    at runSequence (./node_modules/run-sequence/index.js:88:7)
    at ./gulpfile.js:294:10
    at write (./node_modules/gulp-watch/index.js:93:9)
    at ./node_modules/gulp-watch/node_modules/vinyl-file/index.js:51:4
    at evalmachine.<anonymous>:271:14
    at ./node_modules/gulp-watch/node_modules/vinyl-file/node_modules/graceful-fs/graceful-fs.js:102:5
    at Object.oncomplete (evalmachine.<anonymous>:107:15)
```

**Comment by floatdrop** [comment]
If number of listeners is not growing - use [`process.setMaxListeners(0);`](http://stackoverflow.com/questions/9768444/possible-eventemitter-memory-leak-detected).

**Comment by AndyOGo** [comment]
I still get this error too

**Comment by UltCombo** [comment]
@AndyOGo Post your gulpfile please.
Maybe you are likely starting watchers inside a task that is run multiple times?

**Comment by AndyOGo** [comment]
@UltCombo Thanks for your very quick answer.
Well we have that one task `dev` which definitely is executed just once with `gulp dev`. That's it.
But meanwhile I found another fact, we had really old version 1.0.2 installed, so I updated.
