### ISSUE TITLE
Error: watch EMFILE Linux

### ISSUE THREAD

**Issue by pieplu** [floatdrop/gulp-watch#176]
Hi!

Since yesterday, when I try to launch my gulp's task watch, I have this error:

        [15:06:02] Starting 'watch'...
        [15:06:02] Finished 'watch' after 19 ms
        
        events.js:72
                throw er; // Unhandled 'error' event
                      ^
        Error: watch EMFILE
            at errnoException (fs.js:1024:11)
            at FSWatcher.start (fs.js:1056:11)
            at Object.fs.watch (fs.js:1081:11)
            at createFsWatchInstance (/home/apieplu/dev/drupal/dauphine-espace-etudiant/src/drupal/profiles/dauph_profile/themes/dauph_in_front/node_modules/gulp-watch/node_modules/chokidar/lib/nodefs-handler.js:37:15)
            at setFsWatchListener (/home/apieplu/dev/drupal/dauphine-espace-etudiant/src/drupal/profiles/dauph_profile/themes/dauph_in_front/node_modules/gulp-watch/node_modules/chokidar/lib/nodefs-handler.js:80:15)
            at EventEmitter.NodeFsHandler._watchWithNodeFs (/home/apieplu/dev/drupal/dauphine-espace-etudiant/src/drupal/profiles/dauph_profile/themes/dauph_in_front/node_modules/gulp-watch/node_modules/chokidar/lib/nodefs-handler.js:228:14)
            at EventEmitter.NodeFsHandler._handleDir (/home/apieplu/dev/drupal/dauphine-espace-etudiant/src/drupal/profiles/dauph_profile/themes/dauph_in_front/node_modules/gulp-watch/node_modules/chokidar/lib/nodefs-handler.js:403:23)
            at EventEmitter.<anonymous> (/home/apieplu/dev/drupal/dauphine-espace-etudiant/src/drupal/profiles/dauph_profile/themes/dauph_in_front/node_modules/gulp-watch/node_modules/chokidar/lib/nodefs-handler.js:450:19)
            at EventEmitter.<anonymous> (/home/apieplu/dev/drupal/dauphine-espace-etudiant/src/drupal/profiles/dauph_profile/themes/dauph_in_front/node_modules/gulp-watch/node_modules/chokidar/lib/nodefs-handler.js:455:16)
            at Object.oncomplete (fs.js:107:15)

My gulp task looks like this (watch = gulp-watch)
(I don't change anything)

    browsersync.init({
        proxy: "local.dauphine.fr"
    });

    // Watch .scss files
    watch(src_scss + '/**/*.scss', function(event){
		gulp.start('scss-watch');
        
	});

    // Watch .js files
    watch(src_js + '/**/*.js', function(event){
		gulp.start('js-watch');
	});

	// Watch image files
    watch([src_images + '/**/*', "!" + src_images + '/sprite-svg/*.svg'], function(event){
		gulp.start('images-watch');
	});

    // Watch sprite-svg image files
    watch(src_images + '/sprite-svg/*.svg', function(event){
		gulp.start('sprite-watch');
	});

	// Watch prototype
	watch(src_proto + '/**/*', function(event){
		gulp.start('watch-proto');
	});

	// Watch templates
	watch(src_registry, function(event){
		gulp.start('drush-cc');
	});

It's really strange, this morning, after deleted my folder node_module and lauch a new npm install, all works. But after a merge on my working branch with git, it's allready broken.

**Comment by floatdrop** [comment]
I guess this issue belongs to chokidar file watcher, not here.
