### ISSUE TITLE
Error when deleting a foder containing watched file

### ISSUE THREAD

**Issue by ondrejpaluch** [floatdrop/gulp-watch#227]
I use gulp-watch version 4.3.5 with gulpfile as follows:
```` javascript
const gulp   = require('gulp');
const watch  = require('gulp-watch');

function dev_js() {
    return gulp.src('app/**/*.js')
        .pipe(watch('app/**/*.js'))
        .pipe(gulp.dest('build'));
}

gulp.task('default', gulp.parallel(dev_js));
````
Upon deleting a folder that contains a watched file i will get folloving error:

````
[14:04:16] 'dev_js' errored after 17 s
[14:04:16] TypeError: glob pattern string required
    at new Minimatch (C:\Users\JB\Desktop\g4t\node_modules\gulp-watch\node_modules\glob\node_modules\minimatch\minimatch.js:108:11)
    at setopts (C:\Users\JB\Desktop\g4t\node_modules\gulp-watch\node_modules\glob\common.js:112:20)
    at new Glob (C:\Users\JB\Desktop\g4t\node_modules\gulp-watch\node_modules\glob\glob.js:117:3)
    at FSWatcher.processEvent (C:\Users\JB\Desktop\g4t\node_modules\gulp-watch\index.js:92:35)
    at FSWatcher.emit (events.js:110:17)
    at FSWatcher.<anonymous> (C:\Users\JB\Desktop\g4t\node_modules\gulp-watch\node_modules\chokidar\index.js:177:38)
    at FSWatcher._emit (C:\Users\JB\Desktop\g4t\node_modules\gulp-watch\node_modules\chokidar\index.js:217:5)
    at FSWatcher._remove (C:\Users\JB\Desktop\g4t\node_modules\gulp-watch\node_modules\chokidar\index.js:533:50)
    at C:\Users\JB\Desktop\g4t\node_modules\gulp-watch\node_modules\chokidar\index.js:457:20
    at FSReqWrap.oncomplete (fs.js:95:15)
[14:04:16] 'default' errored after 17 s
[14:04:16] TypeError: glob pattern string required
    at new Minimatch (C:\Users\JB\Desktop\g4t\node_modules\gulp-watch\node_modules\glob\node_modules\minimatch\minimatch.js:108:11)
    at setopts (C:\Users\JB\Desktop\g4t\node_modules\gulp-watch\node_modules\glob\common.js:112:20)
    at new Glob (C:\Users\JB\Desktop\g4t\node_modules\gulp-watch\node_modules\glob\glob.js:117:3)
    at FSWatcher.processEvent (C:\Users\JB\Desktop\g4t\node_modules\gulp-watch\index.js:92:35)
    at FSWatcher.emit (events.js:110:17)
    at FSWatcher.<anonymous> (C:\Users\JB\Desktop\g4t\node_modules\gulp-watch\node_modules\chokidar\index.js:177:38)
    at FSWatcher._emit (C:\Users\JB\Desktop\g4t\node_modules\gulp-watch\node_modules\chokidar\index.js:217:5)
    at FSWatcher._remove (C:\Users\JB\Desktop\g4t\node_modules\gulp-watch\node_modules\chokidar\index.js:533:50)
    at C:\Users\JB\Desktop\g4t\node_modules\gulp-watch\node_modules\chokidar\index.js:457:20
    at FSReqWrap.oncomplete (fs.js:95:15)
````

**Comment by UltCombo** [comment]
I'm pretty sure this is fixed in the latest master—this [other fix](https://github.com/floatdrop/gulp-watch/commit/678a8f19fdaf1416b49f40da980b7471dea5e4c6) should at least avoid this issue.

Can you install the package from GitHub (e.g. `npm install floatdrop/gulp-watch`) and check if it works as expected?

**Comment by FunGuyJay** [comment]
I was having the exact same issue for the exact same thing.  I installed `npm install floatdrop/gulp-watch` and deleting the directory works and I don't receive the above error.

**Comment by UltCombo** [comment]
@FunGuyJay Thanks for confirming! :smiley:

I don't have publishing permissions, so I was waiting for @floatdrop to publish a release at an appropriate time. Travis is passing so it should be okay to publish now.

**Comment by floatdrop** [comment]
@FunGuyJay fix published.
